version: 2
updates:
- package-ecosystem: maven
  directory: "/"
  schedule:
    interval: daily
    time: "08:00"
    timezone: "Australia/Brisbane"
  open-pull-requests-limit: 10
  target-branch: "develop"
