name: Update Changelog
on:
  release:
    types:
      - published #only on human interactions, won't be done on github action triggers
  push:
    #On versioned releases
    tags:
      - v*.*.*
  workflow_dispatch:
    inputs:
      description:
        description: 'Manual change log update'
jobs:
  updateChangelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}
          fetch-depth: 0


      - name: Update Changelog
        # https://github.com/git-chglog/git-chglog#getting-started
        run: ./.github/bin/updateChangeLog.sh

      - name: Set up Git username and email
        run: |
          git config --global user.name "${{ vars.GPG_NAME }}"
          git config --global user.email "${{ secrets.GPG_EMAIL }}"
          echo "${{ secrets.GPG_KEY }}" | base64 --decode | gpg --import --no-tty --batch --yes
          #gpg -v --refresh-keys #only needed for external gpg keys
          gpg --list-secret-keys --keyid-format LONG
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}
          git config --global commit.gpgSign true
          git config --global tag.gpgSign true
          git config --global gpg.program gpg

      - name: Create branch/commit
        run: |
          git checkout -b update-changelog
          git add .
          git commit -m"Update changelog"
          git push origin update-changelog --force
          gh pr create --title "Update Changelog" --body "Update changelog to reflect release changes" --base main
        with:
          GH_TOKEN: ${{ github.token }}
